GET http://localhost:8000/version/id=2
Accept: application/json

###
GET http://127.0.0.1:8000/versions/id=1
Accept: application/json

###
# Test your FastAPI endpoints

###
GET http://127.0.0.1:8000/versions/
Accept: application/json

